### PR TITLE
Underscore keys in YAMLs

### LINKED ISSUE #18: Consistent key naming in YAML
Some recently added keys in YAML files (e.g. `normativeStatus`) are camel-cased, presumably by mistake. They should be underscored (e.g. `normative_status`) for consistency sake.

### PR DESCRIPTION
**Pull request by skalee**
Keep YAML style consistent. Always Use underscored keys, never camel cased.

@ronaldtse A new release of data zip is required after merging this one.

Fixes #18.

### CODE REVIEW

**Comment by ronaldtse** [comment]
@skalee this works with me, but pinging @strogonoff on the impact of this.

**Comment by skalee** [comment]
@ronaldtse The impact of this for sure includes need for some trivial changes to IEV site.

**Comment by strogonoff** [comment]
This may require any templates or data reading logic to be updted on depending sites. Would have to grep around a bit

**Comment by skalee** [comment]
Only one template on IEV site. I've adopted underscore convention on the other sites when I migrated them to the new concept model.

**Pull request merged**
